### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by FokkeZB** [Sophrinix/xcode-build-to-device#1]
I get `!AMDeviceSecureInstallApplication` in the end.

**Comment by Sophrinix** [comment]
you should see 
!AMDeviceSecureInstallApplication
OK

The pull request that I just merged in should fix what you are seeing.

What likely happened is that xcode did something (maybe built maybe didn't) and them mobiledevice binary couldn't find the .app file to load. 

Do a git pull on the .b2i directory and try again.

**Comment by Sophrinix** [comment]
The only other problem that I have had is when the xcode project was not built.

I will add a function in the next day or so that rebuilds the xcode project before running b2i. Other than that, this really should just work now.

**Comment by Sophrinix** [comment]
try this again. I now automatically clean the titanium project and rebuild the xcode project every time.
If this is still an issue then please let me know an reopen it.

**Comment by FokkeZB** [comment]
It got it to work now, thx!
